[package]
name = "tron-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
async-trait.workspace = true
pin-project-lite.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
tokio-util.workspace = true
secrecy.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
