[package]
name = "tron-transcription"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ort = { workspace = true }
symphonia = { workspace = true }
rubato = { workspace = true }
hf-hub = { workspace = true }
ndarray = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
